CREATE TABLE log_envio_cobranca (
    id              NUMBER(19)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       NUMBER(19)      NOT NULL REFERENCES tenants(id),
    cobranca_id     NUMBER(19)      NOT NULL REFERENCES cobrancas(id) ON DELETE CASCADE,
    data_tentativa  TIMESTAMP       DEFAULT LOCALTIMESTAMP NOT NULL,
    sucesso         CHAR(1)         DEFAULT 'N' NOT NULL,
    protocolo_sankhya VARCHAR2(255),
    codigo_erro     VARCHAR2(50),
    mensagem_erro   CLOB,
    payload_enviado CLOB            NOT NULL,
    resposta_recebida CLOB,
    url_destino     VARCHAR2(500),
    usuario_id      NUMBER(19)      REFERENCES usuarios(id),
    origem          VARCHAR2(20)    NOT NULL,
    tempo_resposta_ms NUMBER(19),
    hash_registro   VARCHAR2(64)    NOT NULL
);

CREATE INDEX idx_log_envio_cobranca_cobranca_id ON log_envio_cobranca(cobranca_id);
CREATE INDEX idx_log_envio_cobranca_tenant_id ON log_envio_cobranca(tenant_id);
CREATE INDEX idx_log_envio_cobranca_data_tentativa ON log_envio_cobranca(data_tentativa);
CREATE INDEX idx_log_envio_cobranca_sucesso ON log_envio_cobranca(sucesso);
CREATE UNIQUE INDEX idx_log_envio_cobranca_hash ON log_envio_cobranca(cobranca_id, hash_registro);
