CREATE TABLE tenants (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(255) NOT NULL
);

CREATE TABLE usuarios (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id NUMBER(19),
    nome VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL UNIQUE,
    senha VARCHAR2(255) NOT NULL,
    role VARCHAR2(50) NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE TABLE transportadores (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id NUMBER(19) NOT NULL,
    nome VARCHAR2(255) NOT NULL,
    cnpj VARCHAR2(14) NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE TABLE tomadores (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id NUMBER(19) NOT NULL,
    nome VARCHAR2(255) NOT NULL,
    cnpj VARCHAR2(14) NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE TABLE cobrancas (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id NUMBER(19) NOT NULL,
    transportador_id NUMBER(19) NOT NULL,
    tomador_id NUMBER(19) NOT NULL,
    ordem_carga NUMBER(19) NOT NULL,
    tipo_cobranca VARCHAR2(2) NOT NULL,
    tipo_transporte VARCHAR2(1) NOT NULL,
    valor DECIMAL(15, 2) NOT NULL,
    status VARCHAR2(1) NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (transportador_id) REFERENCES transportadores(id),
    FOREIGN KEY (tomador_id) REFERENCES tomadores(id)
);

CREATE TABLE documentos_fiscais (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id NUMBER(19) NOT NULL,
    cobranca_id NUMBER(19) NOT NULL,
    numero NUMBER(19) NOT NULL,
    serie VARCHAR2(50) NOT NULL,
    valor DECIMAL(15, 2) NOT NULL,
    data_emissao DATE NOT NULL,
    data_vencimento DATE NOT NULL,
    base_calculo DECIMAL(15, 2),
    aliquota DECIMAL(5, 2),
    valor_imposto DECIMAL(15, 2),
    chave VARCHAR2(44),
    tipo_doc VARCHAR2(3) NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (cobranca_id) REFERENCES cobrancas(id)
);

CREATE TABLE notas (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id NUMBER(19) NOT NULL,
    documento_fiscal_id NUMBER(19) NOT NULL,
    numero NUMBER(19) NOT NULL,
    serie VARCHAR2(50) NOT NULL,
    data_entrega DATE,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    FOREIGN KEY (documento_fiscal_id) REFERENCES documentos_fiscais(id)
);

-- Inserindo o ADMIN_TENANT padrão (senha: admin, encriptada em BCrypt)
-- Role ADMIN_TENANT não tem tenant_id vinculado (null)
INSERT INTO usuarios (nome, email, senha, role) 
VALUES ('Administrador', 'admin@startquimica.com.br', '$2a$10$2H6O9oXF3uOZhM/KzV2.bOA7tVqj.3Aqy.s1.gV7F./Vn4Q5iUe/2', 'ADMIN_TENANT');
